# Site settings
title: Graph Paper Race Game
description: ""
github: https://github.com/NelsonCrosby/GraphPaperRaceGame
baseurl: /GraphPaperRaceGame

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
